# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alycgaut <alycgaut@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/27 17:20:21 by alycgaut          #+#    #+#              #
#    Updated: 2023/07/27 17:23:55 by alycgaut         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

CC = c++
FLAGS = -Wall -Wextra -werror -std=c++98
RM = rm -rf

all : $(NAME)

$(NAME) :
	$(CC) megaphone.cpp -o $(NAME)

clean :
	$(RM) $(NAME)

re : clean all